### ISSUE TITLE
delay from motion detected to action

### ISSUE THREAD

**Issue by cirrusflyer** [iklein99/homebridge-smartthings#64] opened 2022-10-27 21:05 UTC
**Describe The Bug:**
5-6 second delay from motion sensor detecting motion and lights turning on

**To Reproduce:**
see above

**Expected behavior:**
delay should be less, and was far less in the old Smartthings plugin for Homebridge

**Plugin Config:**

```json
            "name": "Smartthings Plug (IK)",
            "BaseURL": "https://api.smartthings.com/v1/",
            "AccessToken": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "GarageDoorMaxPoll": 40,
            "PollLocksSeconds": 5,
            "PollDoorsSeconds": 10,
            "PollSensorsSeconds": 5,
            "PollSwitchesAndLightsSeconds": 5,
            "IgnoreDevices": [
                "Living Room Christmas Tree",
                "S31 Outlet",
                "Garage Bulb",
                "Motion Sensor 2",
                "Wireless Tag Motion",
                "Shed Door Tag",
                "Laundry Room Water Sensor",
                "Smartthings Water Sensor",
                "Garage Siren",
                "Button",
                "Office Smoke Alarm"
            ],
            "_bridge": {
                "username": "xxxxxxxxxxx",
                "port": 37871
            },
            "platform": "HomeBridgeSmartThings"
```
**Environment:**
1.5.1 Homebridge running on Docker and 1.4.9 of your plugin.

**Comment by veonua** [comment] 2022-10-27 21:12
the plugin does pooling. For pushing you have to setup the https service.

**Comment by cirrusflyer** [comment] 2022-10-27 21:14
No idea what you mean.  It works fine - it's just slow.  What are you talking about?

**Comment by veonua** [comment] 2022-10-27 21:21
Every 10 seconds your Home bridge asks the Smartthings server “what is the status of the sensor”. 

There is a way to subscribe to the ST server notifications, these notifications are way faster and less heavy for ST servers. But Samsung is all about security and willing to send these notifications only to trusted(TLS) servers

**Comment by veonua** [comment] 2022-10-27 21:30
In fact, Samsung closed the old plugin because it is too expensive to host heavy apps in the cloud. 
Pooling many devices too often will affect new servers.

**Comment by cirrusflyer** [comment] 2022-10-28 01:58
Thanks.  So before using this plugin, I was using Homeassistant with the Smartthings integration, and sharing those as a Homekit bridge.  The response was nearly instant.  How is the Homeassistant integration doing it so much faster?  I went to your solution just to make things simpler.

**Comment by veonua** [comment] 2022-10-28 07:37
> How is the Homeassistant integration doing it so much faster?

<sub> ... The preferred approach is to subscribe to Home Assistant Cloud (Nabu Casa) and the integration will configure and use a cloudhook automatically. ... 6.50 USD per month and the annual subscription 65 USD, plus your local sales tax. https://www.home-assistant.io/integrations/smartthings/#webhook<sub>


65 USD per year makes the integration much faster.

**Comment by iklein99** [comment] 2022-10-28 11:46
I really don't know that architecture so I couldn't say.  Samsung has a web hook capability that I looked into a while ago, but it would require each user to set up a domain name and certificate as well as configure port forwarding and perhaps other things on their home network for this to work.  This would allow ST to send events inbound rather than polling which is what this plugin does.  I thought about creating a service but that would start costing $$ and I would have to charge for the use of the plugin to pay for the service.   Didn't want yo go through all of that.  May look to do that in the future.

**Comment by cirrusflyer** [comment] 2022-10-28 13:52
I wasn't paying for any Homeassistant feature, and it was still faster.  But no worries.  It still works, is free, and a nice plugin.  Thanks for the hard work making it happen.

**Comment by iklein99** [comment] 2022-10-28 14:01
Home Assistant supports the web hook capability.  You either have to subscribe to a service for that or do a bunch of work on your own to allow for an inbound web hook call from SmartThings.

In order to do that, you have to have a domain name and certificate.  A lot for people to set up generally.

**Comment by cirrusflyer** [comment] 2022-10-28 14:04
It took me 15 minutes to setup HA in Docker, and I'm using Cloudflare tunnels so the internal proxy and cert is taken care of.  It was easy.  I wouldn't call it a bunch of work.  For those using Homebridge, we already know more about these kinds of things than average Joe.

**Comment by iklein99** [comment] 2022-10-28 14:26
I hear you, but I don’t agree that everyone is as savvy and I’m not willing to handle support questions from everyone that hasn’t done that before.

The best approach would be to handle via a centralized service.

**Comment by iklein99** [comment] 2022-10-28 17:42
I'm closing this as it is working as designed.  I will add an issue as an enhancement to use the web hook (subscription) api for real-time updates.  Have no idea if/when I will be adding that.

**Closed by iklein99** 2022-10-28 17:42 UTC
Labels: bug
