### ISSUE TITLE
What do you need to get locks and shades working?

### ISSUE THREAD

**Issue by veonua** [iklein99/homebridge-smartthings#4] opened 2022-06-12 16:57 UTC
I want to help you with these types of devices, please let me know what is needed

**Comment by iklein99** [comment] 2022-06-12 22:26
If you want, I can add some capabilities for locks and shades, but you'd have to do the testing for me.  Can you commit to doing that?

**Comment by veonua** [comment] 2022-06-13 04:27
yes sure, just let me know what to test.
also you can create a virtual devices

**Comment by iklein99** [comment] 2022-06-14 13:30
I added support for a lock.  Would you be able to test it for me?  I created a beta version for you to test.  To install this, you need to get to a command line and use this command:

sudo npm install -g homebridge-smartthings-ik@beta

Please let me now how you make out.  I am going to add the shade next.

**Comment by veonua** [comment] 2022-06-14 15:05
hmm, installed the plug-in via hombridge UI on my Raspberry Pi, and it seems like there is no npm only pnpm 
do you know if it's possible to install beta via hombridge UI?

**Comment by iklein99** [comment] 2022-06-14 16:42
The issue is that Smartthings doesn't tell hoebridge when something changes, so it may show a bad state.  The same happens with a garage door.  But if you click on the device in Smartthings, it should refresh appropriately.  Its about the best I can do with smartthings.

**Comment by veonua** [comment] 2022-06-14 16:44
can you do 

https://developer-preview.smartthings.com/docs/connected-services/subscriptions/

**Comment by iklein99** [comment] 2022-06-15 18:29
Version 1.1.4 of the plugin now supports locks.

**Comment by veonua** [comment] 2022-06-15 19:00
add shades please

**Comment by iklein99** [comment] 2022-06-16 12:52
Run this command:

curl -H "Authorization: Bearer: <YOUR-ACCESS-TOKEN>" https://api.smartthings.com/v1/devices > devices.json

and send me the output.  i need to see what your window shade looks like.  Replace <YOUR-ACCESS-TOKEN> with your actual token which you used to configure the plugin.  email me the results to iklein99@comcast.net.

**Comment by iklein99** [comment] 2022-06-17 12:00
Please install homebridge-smartthings-ik@1.1.7-beta.0 and let me know if that works for your window shade / blinds.  If it doesn't, please clear out your logs, run homebridge in debug mode and send me the complete logs.

Please let me know if your shade works.

**Comment by veonua** [comment] 2022-06-18 10:59
could you please tell more how do I run in the debug mode

I can see
```
[15/06/2022, 12:37:37] [Smartthings(new)] onGet() FAILED for Living room Curtain. Comm error.
[15/06/2022, 12:37:37] [Smartthings(new)] onGet() FAILED for Right shade. Comm error.
[15/06/2022, 12:37:37] [Smartthings(new)] onGet() FAILED for Curtains. Comm error.
[15/06/2022, 12:37:37] [Smartthings(new)] onGet() FAILED for Left shade. Comm error.
[15/06/2022, 12:37:37] [Smartthings(new)] onGet() FAILED for Central shade. Comm error.
[15/06/2022, 12:37:37] [Smartthings(new)] onGet() FAILED for Second bedroom curtains. Comm error.
```

in my logs

**Comment by iklein99** [comment] 2022-06-18 16:09
Click on the ellipsis (three dots in upper right corner) and click on Homebridge Settings.   



Then toggle on debug mode from there:

**Comment by robjampar** [comment] 2022-08-15 10:16
how about adding a configurable polling request that runs every 30 seconds to resync a device state?

**Comment by robjampar** [comment] 2022-08-15 10:17
> how about adding a configurable polling request that runs every 30 seconds to resync a device state?

**Comment by robjampar** [comment] 2022-08-15 10:18
im running into the same problem (i want to check that the back door lock is locked every night, but i can't do that if it has been locked manually and therefore the plugin still says its unlocked!)

**Comment by robjampar** [comment] 2022-08-15 10:49
something like this

https://github.com/iklein99/homebridge-smartthings/pull/13

(untested)

**Comment by iklein99** [comment] 2022-08-15 17:29
This is a good idea.  I'll look at doing that.  Thanks for the recommendation.

**Comment by iklein99** [comment] 2022-08-15 21:05
Polling for locks has been added.  Closing this item.

**Closed by iklein99** 2022-08-15 21:05 UTC
Labels: enhancement

**Comment by robjampar** [comment] 2022-08-16 08:03
nice!

i've tested this and it needs a minor update, the target state and current state both need to be updated when it syncs


https://github.com/iklein99/homebridge-smartthings/pull/14

**Comment by robjampar** [comment] 2022-08-16 08:05
also this pattern probably could be used for other device types as well
