### ISSUE TITLE
Support for Water Shut-off Valves and Water Leak sensors

### ISSUE THREAD

**Issue by hunkyn** [iklein99/homebridge-smartthings#28] opened 2022-09-16 03:17 UTC
**Is your feature request related to a problem? Please describe:**
I see lights and switches with this automatically showing up. Wanted to see if there is a possibility to add water leak and shut off sensors.

**Comment by iklein99** [comment] 2022-09-16 14:05
I can add that to the list.  I plan to do more support for sensors.  May need you to do some testing for me as I don't have those devices.  I'll let you know shortly.

**Comment by hunkyn** [comment] 2022-09-16 14:30
Sure. I am happy to test. Thank you for quick response.

**Comment by tonymiceli** [comment] 2022-09-19 09:33
I'm also happy to help test as I have a couple of different types of water leak sensors here.

**Comment by drpimples** [comment] 2022-10-06 01:08
You’re mentioning leak sensors but I don’t see mention about zwave valves like the Dome DMWV1 shutoff valve.  I’m happy to beta test.  Thanks!

**Comment by iklein99** [comment] 2022-11-02 18:45
Try version 1.4.12.  I added support for water valves, but they may look like spinklers.   However, will allow you to control just fine.  Let me know.

**Comment by hunkyn** [comment] 2022-11-03 01:06
Thank you. Other than the icon seems like they are working. Will test it further and will keep you posted if any issues.

**Comment by drpimples** [comment] 2022-11-03 01:08
I was hoping this would work.  I ran the update and a full reset to see if it would detect it but no luck.  It’s not showing up in the Homebridge Accessories page.  I wonder if it’s because SmartThings transitioned it over to a new Edge driver.  I checked on my SmartThings iOS app just now and the driver information is dated 2022-11-01.  I noticed this behavior with one of my Zigbee motion sensor not being detected by this plugin.  It too had an Edge driver.  It finally appeared with one your recent plug-in updates.

**Comment by iklein99** [comment] 2022-11-03 13:29
The accessory may not show up as a valve when queried from Smartthings.  

Clear your logs, put homebridge into debug mode and restart.  Wait about 30 seconds then turn off debug.  Send me the log file and let me know the name of the device.

Restart homebridge after you turn debug off.

**Comment by drpimples** [comment] 2022-11-06 20:05
Sorry been busy this week.  How do I send you the logfile directly or securely without posting it for the world to see?

**Comment by iklein99** [comment] 2022-11-07 00:35
You can send directly to me at ***@***.*** Sent from my iPhoneOn Nov 6, 2022, at 3:05 PM, drpimples ***@***.***> wrote:﻿
Sorry been busy this week.  How do I send you the logfile directly or securely without posting it for the world to see?

**Comment by drpimples** [comment] 2022-11-07 00:54
Strange.  Is there a filter in github to screen out email address?  All I saw of your email is ***@***.***

**Comment by drpimples** [comment] 2022-11-07 01:04
I think I was able to send you an email directly.  Let me know if you got it.

**Comment by iklein99** [comment] 2022-11-07 12:41
Ok.  I see the issue and it will be fixed in the next release.

**Comment by drpimples** [comment] 2022-11-07 20:12
Your 4.14 update did it!  The valve now appears on Homekit.  It looks like a sprinkler but that’s okay.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by iklein99** [comment] 2022-11-07 20:18
Confirmed fixed.

**Closed by iklein99** 2022-11-07 20:18 UTC
Labels: enhancement
